name: empower_health

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  dio: ^5.4.1
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.11
  cupertino_icons: ^1.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  pretty_dio_logger: ^1.3.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/