name: empower_health

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  location: ^6.0.2
  flutter_local_notifications: ^17.1.2
  provider: ^6.1.2
  timezone: ^0.9.3
  flutter_native_timezone_updated_gradle: ^2.0.3
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  workmanager: ^0.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  pretty_dio_logger: ^1.3.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/